name: Download PyTorch Build Artifacts

description: Download and unzip artifacts from a previous PyTorch build.

inputs:
  name:
    description: Name of what artifact to download
    required: true
  use-gha:
    description: If set to any value, use GHA to download the artifact. Otherwise use s3.
    required: false
  s3-bucket:
    description: S3 bucket to download builds
    required: false
    default: ""
  is-arc:
    description: Check that we upload the artifact from the PyTorch Foundation bucket.
    type: boolean
    required: false
    default: false

runs:
  using: composite
  steps:
    - name: Download PyTorch Build Artifacts from S3
      if: ${{ !inputs.use-gha && inputs.is-arc == 'false' }}
      uses: seemethere/download-artifact-s3@v4
      with:
        name: ${{ inputs.name }}
        s3-bucket: ${{ inputs.s3-bucket }}

    - name: Download PyTorch Build Artifacts from GHA
      if: ${{ inputs.use-gha && inputs.is-arc == 'false' }}
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.name }}

    - name: Download artifacts from LF
      if: ${{ inputs.is-arc == 'true' }}
      shell: bash
      env:
        REPO: ${{ github.repository }}
        RUN_ID: ${{ github.run_id }}
        NAME: ${{ inputs.name }}
      run: |
        curl -o artifacts.zip https://pytorch-ci-artifacts.s3.amazonaws.com/$REPO/$RUN_ID/$NAME/artifacts.zip

    - name: Unzip artifacts
      shell: bash
      run: |
        ls -la
        unzip -o artifacts.zip

    - name: Output disk space left
      shell: bash
      run: df -H
